name: Meu Primeiro Workflow de CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe RA - Nome
        run: echo "6324073 - Leonardo Fraz찾o Sano"
      - name: Mostra o diret처rio de trabalho
        run: pwd
      - name: Imprime nome do reposit처rio
        run: echo "Nome do reposit처rio: ${{ github.repository }}"
