name: 01 - Nosso Primeiro Workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe RA - Nome
        run: echo "RA - Nome do Aluno"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Imprime nome do repositório
        run: echo "Nome do repositório: ${{ github.repository }}"
